In [108]:
import cv2
import numpy as np
import imageio
from imutils import contours

In [109]:
src = cv2.imread("D:\sudoku11.png")

In [110]:
cv2.imshow("Original Image", src)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [111]:
gray = cv2.cvtColor(src, cv2.COLOR_BGR2GRAY)

In [112]:
print(gray)

[[  0   0   0 ...   0   0   0]
 [  0 255 255 ... 255 255   0]
 [  0 255 255 ... 255 255   0]
 ...
 [  0 255 255 ... 255 255   0]
 [  0 255 255 ... 255 255   0]
 [  0   0   0 ...   0   0   0]]


In [113]:
cv2.imshow("Gray Image", gray)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [114]:
gray = cv2.bitwise_not(gray)
bw = cv2.adaptiveThreshold(gray, 255, cv2.ADAPTIVE_THRESH_MEAN_C, cv2.THRESH_BINARY, 15, -2)

In [115]:
print(bw)

[[255 255 255 ... 255 255 255]
 [255   0   0 ...   0   0 255]
 [255   0   0 ...   0   0 255]
 ...
 [255   0   0 ...   0   0 255]
 [255   0   0 ...   0   0 255]
 [255 255 255 ... 255 255 255]]


In [116]:
cv2.imshow("Black White Image", bw)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [117]:
horizontal = np.copy(bw)
vertical = np.copy(bw)

In [118]:
cols = horizontal.shape[1]
horizontal_size = cols // 10

In [119]:
horizontalStructre = cv2.getStructuringElement(cv2.MORPH_RECT, (horizontal_size, 1))

In [120]:
horizontal = cv2.erode(horizontal, horizontalStructre)
horizontal = cv2.dilate(horizontal, horizontalStructre)

In [121]:
cv2.imshow("Horizontal lines", horizontal)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [122]:
rows = vertical.shape[0]
vertical_size = rows // 10

In [123]:
verticalStructre = cv2.getStructuringElement(cv2.MORPH_RECT, (1, vertical_size))

In [124]:
vertical = cv2.erode(vertical, verticalStructre)
vertical = cv2.dilate(vertical, verticalStructre)

In [125]:
cv2.imshow("Vertical lines", vertical)
cv2.waitKey(0)
cv2.destroyAllWindows()

### NEW ### 

In [126]:
new_image = cv2.bitwise_or(vertical, horizontal)

In [127]:
cv2.imshow("Grids", new_image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [128]:
new_im = cv2.bitwise_not(new_image)

In [129]:
edges =  cv2.adaptiveThreshold(new_im, 255, cv2.ADAPTIVE_THRESH_MEAN_C, cv2.THRESH_BINARY, 3, -2)

In [130]:
cv2.imshow("Concaneted images", edges)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [131]:
kernel = np.ones((2, 2), np.uint8)
edges = cv2.dilate(edges, kernel)

In [132]:
cv2.imshow("dilated edges", edges)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [133]:
smooth = cv2.blur(edges, (2, 2))

In [134]:
cv2.imshow("smooth edges", smooth)
cv2.waitKey(0)
cv2.destroyAllWindows()

### find contours ### 

In [135]:
cnts, hierarchy = cv2.findContours(image=smooth, mode=cv2.RETR_TREE, method=cv2.CHAIN_APPROX_NONE)

In [136]:
cp = src.copy()

In [137]:
cv2.drawContours(image=cp, contours=cnts, contourIdx=-1, color=(0, 0, 255), thickness=2, lineType=cv2.LINE_AA)

array([[[  0,   0, 255],
        [  0,   0, 255],
        [  0,   0, 255],
        ...,
        [  0,   0, 255],
        [  0,   0, 255],
        [  0,   0, 255]],

       [[  0,   0, 255],
        [  0,   0, 255],
        [  0,   0, 255],
        ...,
        [  0,   0, 255],
        [  0,   0, 255],
        [  0,   0, 255]],

       [[  0,   0, 255],
        [  0,   0, 255],
        [ 92,  92, 255],
        ...,
        [  0,   0, 255],
        [  0,   0, 255],
        [  0,   0, 255]],

       ...,

       [[  0,   0, 255],
        [  0,   0, 255],
        [  0,   0, 255],
        ...,
        [  0,   0, 255],
        [  0,   0, 255],
        [  0,   0, 255]],

       [[  0,   0, 255],
        [  0,   0, 255],
        [  0,   0, 255],
        ...,
        [  0,   0, 255],
        [  0,   0, 255],
        [  0,   0, 255]],

       [[  0,   0, 255],
        [  0,   0, 255],
        [  0,   0, 255],
        ...,
        [  0,   0, 255],
        [  0,   0, 255],
        [  0,   0, 255]]

In [138]:
cv2.imshow("detected contours", cp)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [139]:
cnts, _ = contours.sort_contours(cnts, method="left-to-right")
cnts, _ = contours.sort_contours(cnts, method="top-to-bottom")

### plot contours ###

In [140]:
cp = src.copy()
count = 0

for c in cnts:
    if cv2.contourArea(c) > 1000 and cv2.contourArea(c) < 5000:
        count += 1
        rect = cv2.boundingRect(c)
        x, y, w, h = rect
        cv2.rectangle(cp, (x, y), (x+w, y+h), (0, 255, 0), 2)
        cv2.imshow("black white image", cp)
        cv2.waitKey(500)
cv2.destroyAllWindows()

In [141]:
!pip install pytesseract

Defaulting to user installation because normal site-packages is not writeable


In [143]:
import pytesseract
import os
import cv2

# pytesseract.pytesseract.tesseract_cmd = r'C:\Program Files\Tesseract-OCR\tesseract.exe'

def convert_gray(img):
    im = cv2.imread(img)
    return cv2.cvtColor(im, cv2.COLOR_BGR2GRAY)

def get_num(img):
    return pytesseract.image_to_string(img, config=r'--oem 1 --psm 13 outputbase digits')

In [144]:
import imageio
import cv2

cp = src.copy()
count = 0
num = []
for c in cnts:
    if cv2.contourArea(c) > 1000 and cv2.contourArea(c) < 5000:
        count += 1
        rect = cv2.boundingRect(c)
        x, y, w, h = rect
        array = np.array(cp[y:y+h, x:x+w])
        num.append(get_num(array))


In [145]:
len(num)

81

In [146]:
def divide_chunks(l, n):
    for i in range(0, len(l), n):
        yield l[i: i+n]
        
n = 9
matrix = list(divide_chunks(num, n))
print(matrix)

[['', '7\n', '', '5\n', '8\n', '3\n', '', '2\n', ''], ['', '5\n', '9\n', '2\n', '', '', '3\n', '', ''], ['3\n', '4\n', '', '', '', '6\n', '5\n', '', '7\n'], ['7\n', '9\n', '5\n', '', '', '', '6\n', '3\n', '2\n'], ['', '', '3\n', '6\n', '9\n', '7\n', '1\n', '', ''], ['6\n', '8\n', '', '', '', '2\n', '7\n', '', ''], ['9\n', '1\n', '4\n', '8\n', '3\n', '5\n', '', '7\n', '6\n'], ['', '3\n', '', '7\n', '', '1\n', '4\n', '9\n', '5\n'], ['5\n', '6\n', '7\n', '4\n', '2\n', '9\n', '', '1\n', '3\n']]


In [147]:
import copy
mat = copy.deepcopy(matrix)

for n in mat:
    for j,i in enumerate(n):
        if i == "":
            n[j]=i.replace("", "0")
        else:
            n[j]=i.replace(i, i[0])

In [148]:
mat

[['0', '7', '0', '5', '8', '3', '0', '2', '0'],
 ['0', '5', '9', '2', '0', '0', '3', '0', '0'],
 ['3', '4', '0', '0', '0', '6', '5', '0', '7'],
 ['7', '9', '5', '0', '0', '0', '6', '3', '2'],
 ['0', '0', '3', '6', '9', '7', '1', '0', '0'],
 ['6', '8', '0', '0', '0', '2', '7', '0', '0'],
 ['9', '1', '4', '8', '3', '5', '0', '7', '6'],
 ['0', '3', '0', '7', '0', '1', '4', '9', '5'],
 ['5', '6', '7', '4', '2', '9', '0', '1', '3']]

In [149]:
for row in mat:
    for j,i in enumerate(row):
        row[j] = int(i)

In [150]:
mat

[[0, 7, 0, 5, 8, 3, 0, 2, 0],
 [0, 5, 9, 2, 0, 0, 3, 0, 0],
 [3, 4, 0, 0, 0, 6, 5, 0, 7],
 [7, 9, 5, 0, 0, 0, 6, 3, 2],
 [0, 0, 3, 6, 9, 7, 1, 0, 0],
 [6, 8, 0, 0, 0, 2, 7, 0, 0],
 [9, 1, 4, 8, 3, 5, 0, 7, 6],
 [0, 3, 0, 7, 0, 1, 4, 9, 5],
 [5, 6, 7, 4, 2, 9, 0, 1, 3]]

In [151]:
grid = copy.deepcopy(mat)

### SOLVER

In [152]:
M = 9
def puzzle(a):
    for i in range(M):
        for j in range(M):
            print(a[i][j],end = " ")
        print()
def solve(grid, row, col, num):
    for x in range(9):
        if grid[row][x] == num:
            return False
        
    for x in range(9):
        if grid[x][col] == num:
            return False


    startRow = row - row % 3
    startCol = col - col % 3
    for i in range(3):
        for j in range(3):
            if grid[i + startRow][j + startCol] == num:
                return False
    return True

def Suduko(grid, row, col):

    if (row == M - 1 and col == M):
        return True
    if col == M:
        row += 1
        col = 0
    if grid[row][col] > 0:
        return Suduko(grid, row, col + 1)
    for num in range(1, M + 1, 1): 
    
        if solve(grid, row, col, num):
        
            grid[row][col] = num
            if Suduko(grid, row, col + 1):
                return True
        grid[row][col] = 0
    return False


if (Suduko(grid, 0, 0)):
    puzzle(grid)
else:
    print("Solution does not exist:(")

1 7 6 5 8 3 9 2 4 
8 5 9 2 7 4 3 6 1 
3 4 2 9 1 6 5 8 7 
7 9 5 1 4 8 6 3 2 
4 2 3 6 9 7 1 5 8 
6 8 1 3 5 2 7 4 9 
9 1 4 8 3 5 2 7 6 
2 3 8 7 6 1 4 9 5 
5 6 7 4 2 9 8 1 3 


In [153]:
bound = []
count = 0
for c in cnts:
    if cv2.contourArea(c) > 1000 and cv2.contourArea(c) < 5000:
        count += 1
        rect = cv2.boundingRect(c)
        bound.append(rect)

In [154]:
len(bound)

81

In [155]:
grid

[[1, 7, 6, 5, 8, 3, 9, 2, 4],
 [8, 5, 9, 2, 7, 4, 3, 6, 1],
 [3, 4, 2, 9, 1, 6, 5, 8, 7],
 [7, 9, 5, 1, 4, 8, 6, 3, 2],
 [4, 2, 3, 6, 9, 7, 1, 5, 8],
 [6, 8, 1, 3, 5, 2, 7, 4, 9],
 [9, 1, 4, 8, 3, 5, 2, 7, 6],
 [2, 3, 8, 7, 6, 1, 4, 9, 5],
 [5, 6, 7, 4, 2, 9, 8, 1, 3]]

In [156]:
mat

[[0, 7, 0, 5, 8, 3, 0, 2, 0],
 [0, 5, 9, 2, 0, 0, 3, 0, 0],
 [3, 4, 0, 0, 0, 6, 5, 0, 7],
 [7, 9, 5, 0, 0, 0, 6, 3, 2],
 [0, 0, 3, 6, 9, 7, 1, 0, 0],
 [6, 8, 0, 0, 0, 2, 7, 0, 0],
 [9, 1, 4, 8, 3, 5, 0, 7, 6],
 [0, 3, 0, 7, 0, 1, 4, 9, 5],
 [5, 6, 7, 4, 2, 9, 0, 1, 3]]

In [157]:
n = 9
bound = list(divide_chunks(bound, n))
print(bound)

[[(3, 3, 61, 61), (67, 3, 61, 61), (131, 3, 60, 61), (196, 3, 60, 61), (259, 3, 61, 61), (323, 3, 60, 61), (388, 3, 60, 61), (451, 3, 61, 61), (515, 3, 61, 61)], [(3, 67, 61, 61), (67, 67, 61, 61), (131, 67, 60, 61), (196, 67, 60, 61), (259, 67, 61, 61), (323, 67, 60, 61), (388, 67, 60, 61), (451, 67, 61, 61), (515, 67, 61, 61)], [(3, 131, 61, 60), (67, 131, 61, 60), (131, 131, 60, 60), (196, 131, 60, 60), (259, 131, 61, 60), (323, 131, 60, 60), (388, 131, 60, 60), (451, 131, 61, 60), (515, 131, 61, 60)], [(3, 196, 61, 60), (67, 196, 61, 60), (131, 196, 60, 60), (196, 196, 60, 60), (259, 196, 61, 60), (323, 196, 60, 60), (388, 196, 60, 60), (451, 196, 61, 60), (515, 196, 61, 60)], [(3, 259, 61, 61), (67, 259, 61, 61), (131, 259, 60, 61), (196, 259, 60, 61), (259, 259, 61, 61), (323, 259, 60, 61), (388, 259, 60, 61), (451, 259, 61, 61), (515, 259, 61, 61)], [(3, 323, 61, 60), (67, 323, 61, 60), (131, 323, 60, 60), (196, 323, 60, 60), (259, 323, 61, 60), (323, 323, 60, 60), (388, 323, 60

In [158]:
cp = src.copy()

for i, m in enumerate(mat):
    for j, n in enumerate(m):
        if mat[i][j] != grid[i][j]:
            x, y, w, h = bound[i][j]
            cv2.putText(cp, str(grid[i][j]), (x+w-40, y+h-20), 0, 0.9, (0, 0, 255))

In [159]:
cv2.imshow("Example", cp)
cv2.waitKey(0)
cv2.destroyAllWindows()